import type { Metadata } from "next";
import { Rajdhani } from "next/font/google";
import Footer from "./components/Footer";
import "./globals.css";
import Navbar from "./Navbar";

const rajdhani = Rajdhani({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rajdhani.className}>
        <Navbar />
        <main className="pb-[8%] sm:mb-[18%]"> {children}</main>

        <Footer />
      </body>
    </html>
  );
}
